import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Components/CustomComp/Navbar'
import Footer from './Components/CustomComp/Footer'
import GlobalContextProvider from './Components/Context/GlobalContextProvider'
import GloabalSnackBar from './Components/CustomComp/GloabalSnackBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">

            <body className={inter.className}>
                <GlobalContextProvider>
                    <Navbar></Navbar>
                    {children}
                    <Footer></Footer>
                    <GloabalSnackBar></GloabalSnackBar>
                </GlobalContextProvider>

            </body>
        </html>
    )
}
