import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import Navbar from './Components/CustomComp/Navbar'
import Footer from './Components/CustomComp/Footer'
import GlobalContextProvider from './Components/Context/GlobalContextProvider'
import GlobalSnackBar from './Components/CustomComp/GloabalSnackBar'
import NextAuthSessionProvider from './Components/Context/NextAuthSessionProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">

            <body className={inter.className}>
                <GlobalContextProvider>
                    <NextAuthSessionProvider>
                        <Navbar></Navbar>
                        {children}
                        <Footer></Footer>
                        <GlobalSnackBar></GlobalSnackBar>
                    </NextAuthSessionProvider>
                </GlobalContextProvider>

            </body>
        </html>
    )
}
